version: '3'
services:
  clickhouse-server:
    image: yandex/clickhouse-server:latest
    ports:
      - "${CLICKHOUSE_PORT:-9000}:9000"
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    env_file:
      - .env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${CLICKHOUSE_HTTP_PORT:-8123}/ping || exit 1
    restart: unless-stopped
  
  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    

volumes:
  clickhouse_data:
